#file: noinspection SpellCheckingInspection
run:
  concurrency: 4
  timeout: 30m

linters-settings:
  cyclop:
    max-complexity: 15
  goconst:
    ignore-tests: true
    match-constant: false
  gomnd:
    ignored-numbers:
      - '0644'
      - '0755'
  gosec:
    config:
      G306: "0644"
  govet:
    enable-all: true
    disable:
      - fieldalignment
  lll:
    line-length: 160
  nolintlint:
    require-explanation: true
    require-specific: true
  nonamedreturns:
    report-error-in-defer: true
  stylecheck:
    dot-import-whitelist: []
    http-status-code-whitelist: []
    checks: ["all", "-ST1000", "-ST1003", "-ST1020", "-ST1021", "-ST1022"]
  usestdlibvars:
    time-month: true
    time-layout: true
    crypto-hash: true
    default-rpc-path: true
    tls-signature-scheme: true
    constant-kind: true
  exhaustive:
    default-signifies-exhaustive: true

# https://golangci-lint.run/usage/configuration/#linters-configuration
linters:
  disable-all: true
  enable:
    - asasalint
    - bodyclose
    - containedctx
    - cyclop
    - dogsled
    - errcheck
    - errname
    - errorlint
    - exhaustive
    - copyloopvar
    - forbidigo
    - funlen
    - gochecknoinits
    - goconst
    - gocritic
    - err113
    - mnd
    - gomoddirectives
    - goprintffuncname
    - gosec
    - gosimple
    - govet
    - grouper
    - ineffassign
    - lll
    - misspell
    - nilerr
    - noctx
    - nolintlint
    - nonamedreturns
    - prealloc
    - predeclared
    - revive
    - staticcheck
    - stylecheck
    - tenv
    - typecheck
    - unconvert
    - unparam
    - unused
    - usestdlibvars
    - wastedassign
    - whitespace

issues:
  exclude-dirs:
    - vendor
    - mocks
  max-same-issues: 0
  max-issues-per-linter: 0
  exclude-rules:
    - linters:
        - staticcheck
      text: 'SA1019:'
    - text: 'shadow: declaration of "(err|ctx)" shadows declaration at'
      linters: [ govet ]
    - path: _test\.go
      linters:
        - errcheck
        - funlen
        - gocyclo
        - goerr113
        - gomnd
        - gosec
        - lll
